
CREATE PROCEDURE usp_getCOMMENTSbyMEDIAID
	@MEDIAID INT
AS
BEGIN
	;WITH COMMENT_Tree AS (
    SELECT c.COMMENTID, c.PARENTID
    FROM COMMENTS c
		JOIN MEDIACOMMENTS mc ON c.COMMENTID = mc.COMMENTID
		JOIN MEDIA m ON mc.MEDIAID = m.ID
	WHERE m.ID = @MEDIAID
		AND PARENTID IS NULL
    UNION ALL
    SELECT c.COMMENTID, c.PARENTID
    FROM COMMENTS c
		JOIN COMMENT_Tree t ON c.PARENTID = t.COMMENTID
	)
	
	SELECT c.COMMENTID
		,c.PARENTID
		,c.TEXT
		,c.DELETED
		,COALESCE(c.MODIFIEDDATE, c.CREATEDDATE) MODIFIEDDATE
		,u.USERNAME
	FROM COMMENTS c
		JOIN COMMENT_Tree t ON c.COMMENTID = t.COMMENTID
		JOIN USERS u on c.USERID = u.USERID
	ORDER BY PARENTID, COMMENTID
END
