
CREATE PROCEDURE usp_insMEDIA
	@TITLE NVARCHAR(60),
	@MEDIATYPEID INT,
	@YEARRELEASED INT,
	@DESCRIPTION NVARCHAR(MAX),
	@IMAGEURL VARCHAR(200)
AS
BEGIN
	INSERT INTO MEDIA (TITLE, MEDIATYPEID, YEARRELEASED, DESCRIPTION, IMAGEURL) 
	VALUES (@TITLE, @MEDIATYPEID, @YEARRELEASED, @DESCRIPTION, @IMAGEURL)
END
