
CREATE PROCEDURE usp_updUSERS
	@USERID INT,
	@FIRSTNAME NVARCHAR(55),
	@LASTNAME NVARCHAR(55),
	@EMAILADDRESS VARCHAR(100)
AS
BEGIN
	UPDATE USERS
	SET FIRSTNAME = @FIRSTNAME
		,LASTNAME = @LASTNAME
		,EMAILADDRESS = @EMAILADDRESS
	WHERE USERID = @USERID
END
