
CREATE PROCEDURE usp_upsertMEDIARATING
	@USERID INT,
	@MEDIAID INT,
	@RATING INT
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN

		IF EXISTS (SELECT 1 FROM MEDIARATINGS WITH (UPDLOCK) WHERE USERID = @USERID AND MEDIAID = @MEDIAID)
		BEGIN
			UPDATE MEDIARATINGS
			SET RATING = @RATING
			WHERE USERID = @USERID
				AND MEDIAID = @MEDIAID
		END
		ELSE
		BEGIN 
			INSERT INTO MEDIARATINGS (USERID, MEDIAID, RATING) VALUES (@USERID, @MEDIAID, @RATING)
		END
	
	COMMIT
END