
CREATE PROCEDURE usp_insUSERS
	@USERNAME VARCHAR(50),
	@PASSWORD NVARCHAR(255),
	@FIRSTNAME NVARCHAR(55),
	@LASTNAME NVARCHAR(55),
	@EMAILADDRESS VARCHAR(100),
	@SALT VARCHAR(100),
	@ROLEID VARCHAR(100)
AS
BEGIN
	INSERT INTO USERS (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAILADDRESS, SALT, ROLEID)
	VALUES (@USERNAME, @PASSWORD, @FIRSTNAME, @LASTNAME, @EMAILADDRESS, @SALT, @ROLEID)
END
