
CREATE PROCEDURE usp_getCOMMENTSbyUSERNAME
	@USERNAME VARCHAR(50)
AS
BEGIN
	SELECT c.COMMENTID
		,c.PARENTID
		,c.TEXT
		,c.DELETED
		,COALESCE(c.MODIFIEDDATE, c.CREATEDDATE) MODIFIEDDATE
		,u.USERNAME
	FROM COMMENTS c
		JOIN USERS u on c.USERID = u.USERID
	WHERE u.USERNAME = @USERNAME
	ORDER BY CREATEDDATE
END
