
CREATE PROCEDURE usp_getChildCOMMENTS
	@COMMENTID INT
AS
BEGIN
	;WITH COMMENT_Tree AS (
    SELECT c.COMMENTID, c.PARENTID
    FROM COMMENTS c
	WHERE COMMENTID = @COMMENTID
    UNION ALL
    SELECT c.COMMENTID, c.PARENTID
    FROM COMMENTS c
		JOIN COMMENT_Tree t ON c.PARENTID = t.COMMENTID
	)
	
	SELECT c.COMMENTID
		,c.PARENTID
		,c.TEXT
		,c.DELETED
		,COALESCE(c.MODIFIEDDATE, c.CREATEDDATE) MODIFIEDDATE
		,u.USERNAME
	FROM COMMENTS c
		JOIN COMMENT_Tree t ON c.COMMENTID = t.COMMENTID
		JOIN USERS u on c.USERID = u.USERID
	ORDER BY PARENTID, COMMENTID
END
