
CREATE PROCEDURE usp_getCOMMENTSbyUSERID
	@USERID INT
AS
BEGIN
	SELECT c.COMMENTID
		,c.PARENTID
		,c.TEXT
		,c.DELETED
		,COALESCE(c.MODIFIEDDATE, c.CREATEDDATE) MODIFIEDDATE
		,u.USERNAME
	FROM COMMENTS c
		JOIN USERS u on c.USERID = u.USERID
	WHERE c.USERID = @USERID
	ORDER BY CREATEDDATE
END
