
CREATE PROCEDURE usp_insCOMMENT
	@USERID INT,
	@MEDIAID INT,
	@PARENTID INT,
	@TEXT NVARCHAR(MAX)
AS
BEGIN
	DECLARE @COMMENT TABLE (COMMENTID INT)

	INSERT INTO COMMENTS (PARENTID, USERID, TEXT) OUTPUT (INSERTED.COMMENTID) INTO @COMMENT VALUES (@PARENTID, @USERID, @TEXT)

	INSERT INTO USERMEDIACOMMENTS (MEDIAID, COMMENTID) 
	SELECT @MEDIAID, COMMENTID FROM @COMMENT
END
