CREATE TABLE [dbo].[COMMENTS] (
    [COMMENTID]    INT            IDENTITY (1, 1) NOT NULL,
    [PARENTID]     INT            NULL,
    [USERID]       INT            NULL,
    [TEXT]         NVARCHAR (MAX) NULL,
    [DELETED]      BIT            DEFAULT ((0)) NULL,
    [CREATEDDATE]  DATETIME       DEFAULT (getdate()) NULL,
    [MODIFIEDBY]   VARCHAR (50)   DEFAULT (NULL) NULL,
    [MODIFIEDDATE] DATETIME       DEFAULT (NULL) NULL,
    PRIMARY KEY CLUSTERED ([COMMENTID] ASC),
    FOREIGN KEY ([PARENTID]) REFERENCES [dbo].[COMMENTS] ([COMMENTID]),
    FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([USERID])
);


GO
CREATE NONCLUSTERED INDEX [IX_COMMENTS_COMMENTID_PARENTID]
    ON [dbo].[COMMENTS]([COMMENTID] ASC, [PARENTID] ASC)
    INCLUDE([TEXT], [DELETED], [CREATEDDATE], [MODIFIEDBY], [MODIFIEDDATE]);

