CREATE TABLE [dbo].[MEDIARATINGS] (
    [USERID]  INT NOT NULL,
    [MEDIAID] INT NOT NULL,
    [RATING]  INT NOT NULL,
    PRIMARY KEY CLUSTERED ([USERID] ASC, [MEDIAID] ASC),
    FOREIGN KEY ([MEDIAID]) REFERENCES [dbo].[MEDIA] ([ID]),
    FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([USERID])
);

