CREATE TABLE [dbo].[MEDIACOMMENTS] (
    [MEDIAID]   INT NOT NULL,
    [COMMENTID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MEDIAID] ASC, [COMMENTID] ASC),
    FOREIGN KEY ([COMMENTID]) REFERENCES [dbo].[COMMENTS] ([COMMENTID]),
    FOREIGN KEY ([MEDIAID]) REFERENCES [dbo].[MEDIA] ([ID])
);

