CREATE TABLE [dbo].[MEDIA] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [TITLE]        NVARCHAR (60)  NOT NULL,
    [MEDIATYPEID]  INT            NULL,
    [YEARRELEASED] INT            NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    [IMAGEURL]     VARCHAR (400)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([MEDIATYPEID]) REFERENCES [dbo].[MEDIATYPE] ([TYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_MEDIA_TITLE]
    ON [dbo].[MEDIA]([TITLE] ASC)
    INCLUDE([YEARRELEASED], [DESCRIPTION], [IMAGEURL]);

