CREATE TABLE [dbo].[USERS] (
    [USERID]       INT            IDENTITY (1, 1) NOT NULL,
    [USERNAME]     VARCHAR (50)   NULL,
    [PASSWORD]     NVARCHAR (255) NULL,
    [FIRSTNAME]    NVARCHAR (55)  NULL,
    [LASTNAME]     NVARCHAR (55)  NULL,
    [EMAILADDRESS] VARCHAR (100)  NULL,
    [SALT]         VARCHAR (100)  NULL,
    [ROLEID]       INT            NULL,
    PRIMARY KEY CLUSTERED ([USERID] ASC),
    FOREIGN KEY ([ROLEID]) REFERENCES [dbo].[ROLES] ([ROLEID]),
    UNIQUE NONCLUSTERED ([USERNAME] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_USERS_USERNAME_SALT_PASSWORD_ROLE]
    ON [dbo].[USERS]([USERNAME] ASC, [SALT] ASC, [PASSWORD] ASC, [ROLEID] ASC);

