USE master
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'MediaRater')
BEGIN
	DROP DATABASE MediaRater
END

CREATE DATABASE MediaRater
GO

USE MediaRater
GO

CREATE TABLE USERS
(
	USERID INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME VARCHAR(50) UNIQUE,
	PASSWORD NVARCHAR(255),
	FIRSTNAME NVARCHAR(55),
	LASTNAME NVARCHAR(55),
	EMAILADDRESS VARCHAR(100),
	SALT VARCHAR(100),
	ROLE VARCHAR(100)
)
GO

CREATE INDEX IX_USERS_USERNAME_SALT_PASSWORD_ROLE ON USERS (USERNAME, SALT, PASSWORD, ROLE)
GO

CREATE TABLE MEDIA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TITLE NVARCHAR(60) NOT NULL,
	YEARRELEASED INT,
	DESCRIPTION NVARCHAR(MAX),
	IMAGEURL VARCHAR(200)
)
GO

CREATE INDEX IX_MEDIA_TITLE ON MEDIA (TITLE) INCLUDE (YEARRELEASED, DESCRIPTION, IMAGEURL)
GO

CREATE TABLE MEDIARATINGS
(
	USERID INT FOREIGN KEY REFERENCES USERS(USERID),
	MEDIAID INT FOREIGN KEY REFERENCES MEDIA(ID),
	RATING INT NOT NULL,
	PRIMARY KEY (USERID, MEDIAID)
)
GO

CREATE TABLE COMMENTS
(
	COMMENTID INT IDENTITY(1,1) PRIMARY KEY,
	PARENTID INT FOREIGN KEY REFERENCES COMMENTS(COMMENTID) NULL,
	TEXT NVARCHAR(MAX),
	DELETED BIT DEFAULT 0,
	CREATEDDATE DATETIME DEFAULT GETDATE(),
	MODIFIEDBY VARCHAR(50) NULL,
	MODIFIEDDATE DATETIME NULL
)
GO

CREATE INDEX IX_COMMENTS_COMMENTID_PARENTID ON COMMENTS (COMMENTID, PARENTID) INCLUDE (TEXT, DELETED, CREATEDDATE, MODIFIEDBY, MODIFIEDDATE)
GO

CREATE TABLE USERMEDIACOMMENTS
(
	USERID INT FOREIGN KEY REFERENCES USERS(USERID),
	MEDIAID INT FOREIGN KEY REFERENCES MEDIA(ID),
	COMMENTID INT FOREIGN KEY REFERENCES COMMENTS(COMMENTID),
	PRIMARY KEY (USERID,MEDIAID,COMMENTID)
)
GO

CREATE PROCEDURE usp_insUSERS
	@USERNAME VARCHAR(50),
	@PASSWORD NVARCHAR(255),
	@FIRSTNAME NVARCHAR(55),
	@LASTNAME NVARCHAR(55),
	@EMAILADDRESS VARCHAR(100),
	@SALT VARCHAR(100),
	@ROLE VARCHAR(100)
AS
BEGIN
	INSERT INTO USERS (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAILADDRESS, SALT, ROLE)
	VALUES (@USERNAME, @PASSWORD, @FIRSTNAME, @LASTNAME, @EMAILADDRESS, @SALT, @ROLE)
END
GO

CREATE PROCEDURE usp_updUSERS
	@USERID INT,
	@FIRSTNAME NVARCHAR(55),
	@LASTNAME NVARCHAR(55),
	@EMAILADDRESS VARCHAR(100)
AS
BEGIN
	UPDATE USERS
	SET FIRSTNAME = @FIRSTNAME
		,LASTNAME = @LASTNAME
		,EMAILADDRESS = @EMAILADDRESS
	WHERE USERID = @USERID
END
GO

CREATE PROCEDURE usp_updUSERS_ROLE
	@USERID INT,
	@ROLE VARCHAR(100)
AS
BEGIN
	UPDATE USERS
	SET ROLE = @ROLE
	WHERE USERID = @USERID
END
GO

CREATE PROCEDURE usp_updUSERS_PASSWORD
	@USERID INT,
	@PASSWORD NVARCHAR(255)
AS
BEGIN
	UPDATE USERS
	SET PASSWORD = @PASSWORD
	WHERE USERID = @USERID
END
GO

CREATE PROCEDURE usp_delUSER
	@USERID INT
AS
BEGIN
	DELETE FROM USERS WHERE USERID = @USERID
END

